#!/usr/bin/env python3

from PIL import Image
import sys
import math
import argparse


def check_validity(img1, img2):
    if (img1.size != img2.size):
        sys.exit("Input images have different dimensions")


# Define a function to compute the color distance between two pixels in LAB space
# This basically allows slightly different pixels to be seen as identical
def color_distance(rgb1, rgb2):
    r1, g1, b1 = rgb1[:3]
    r2, g2, b2 = rgb2[:3]
    # Convert RGB values to LAB values
    xyz1 = (0.412453*r1 + 0.357580*g1 + 0.180423*b1, 0.212671*r1 + 0.715160*g1 + 0.072169*b1, 0.019334*r1 + 0.119193*g1 + 0.950227*b1)
    xyz2 = (0.412453*r2 + 0.357580*g2 + 0.180423*b2, 0.212671*r2 + 0.715160*g2 + 0.072169*b2, 0.019334*r2 + 0.119193*g2 + 0.950227*b2)
    lab1 = (116 * math.pow(xyz1[1]/1.0, 1/3) - 16, 500 * (math.pow(xyz1[0]/0.95047, 1/3) - math.pow(xyz1[1]/1.0, 1/3)), 200 * (math.pow(xyz1[1]/1.0, 1/3) - math.pow(xyz1[2]/1.08883, 1/3)))
    lab2 = (116 * math.pow(xyz2[1]/1.0, 1/3) - 16, 500 * (math.pow(xyz2[0]/0.95047, 1/3) - math.pow(xyz2[1]/1.0, 1/3)), 200 * (math.pow(xyz2[1]/1.0, 1/3) - math.pow(xyz2[2]/1.08883, 1/3)))
    # Compute the distance between the colors in LAB space
    return math.sqrt(math.pow(lab1[0]-lab2[0], 2) + math.pow(lab1[1]-lab2[1], 2) + math.pow(lab1[2]-lab2[2], 2))


def write_to_output(image1, image2, args, size):
    print("Comparing pixels...")

    output_img = Image.new("RGB", size, color=(255, 255, 255))

    width, height = size
    color_threshold = args.threshold

    diff_pixel = 0

    for x in range(width):
        for y in range(height):
            # Get the pixel values of the two images at this location
            pixel1 = image1.getpixel((x, y))
            pixel2 = image2.getpixel((x, y))

            # Compare the pixel values
            dist = color_distance(pixel1, pixel2)
            if dist >= color_threshold:
                output_img.putpixel((x, y), (200, 40, 25))
                diff_pixel += 1

    if (diff_pixel > 0):
        print("Writing to output image")
        output_img.save(args.output)

    else:
        print("The images are identical")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('image1', type=str, help="first input file")
    parser.add_argument('image2', type=str, help="second input file")
    parser.add_argument('--output', type=str, required=False,
                        help="output filename defaults to diff.png", default="diff.png")
    parser.add_argument("--threshold", type=float, required=False,
               help="colors threshold to specify an acceptable range of difference in pixels, defaults to 10", default=10.0)

    args = parser.parse_args()

    image1 = Image.open(args.image1)
    image2 = Image.open(args.image2)

    check_validity(image1, image2)

    size = image1.size
    write_to_output(image1, image2, args, size)


if __name__ == "__main__":
    main()
